outwatch/outwatch

src/main/scala/outwatch/util/Store.scala
Hi,
IMHO, `Store[T, U]` is not very readable and so not very easy to understand for newbies, like me, of ELM architecture so I improved it a little. 
And I added return types because it could also help newbies to understand what your code do and why it's useful.
=> Improve Store code readability

src/main/scala/outwatch/dom/VDomModifier.scala, src/main/scala/outwatch/dom/helpers/DomUtils.scala, src/main/scala/snabbdom/VDomProxy.scala, src/main/scala/snabbdom/h.scala, src/test/scala/outwatch/OutWatchDomSpec.scala, src/test/scala/outwatch/ScenarioTestSpec.scala
This PR fixes issue #38.
The patch assigns a key to a VNode's data object that contains changeables and doesn't already have a key in order to force Snabbdom to destroy/re-create it when patched with new changeables. It also fixes the ```DataObject.updateAttributes``` method by passing the key to the newly constructed ```DataObject```.
I've also been doing some refactoring, most notably turned DataObject and Hooks in the Snabbdom facade into ```@ScalaJSDefined``` traits for extra type safety (this would have prevented the ```DataObject.updateAttributes``` bug for example).
=> Fix Snabbdom patching issue

src/main/scala/outwatch/Sink.scala, src/main/scala/outwatch/dom/Handlers.scala, src/main/scala/outwatch/dom/package.scala, src/main/scala/outwatch/util/Store.scala, src/main/scala/outwatch/util/WebSocket.scala
A few refactorings in ```Sink```, made a code a bit more DRY, added ```onError``` and ```onComplete``` arguments to ```Sink.create```.
=> Some refactorings in Sink

src/main/scala/outwatch/dom/VDomModifier.scala, src/main/scala/outwatch/dom/helpers/Builder.scala, src/main/scala/outwatch/dom/helpers/DomUtils.scala, src/test/scala/outwatch/AttributeSpec.scala, src/test/scala/outwatch/OutWatchDomSpec.scala
This is my attempt to fix #22. Does it make sense to you?
=> support optional elements and attributes

src/main/scala/outwatch/dom/VDomModifier.scala, src/main/scala/outwatch/dom/helpers/Builder.scala, src/main/scala/snabbdom/VDomProxy.scala, src/main/scala/snabbdom/h.scala, src/test/scala/outwatch/DomEventSpec.scala, src/test/scala/outwatch/OutWatchDomSpec.scala, src/test/scala/outwatch/SnabbdomSpec.scala
The current behaviour of how we handle boolean attributes seems to be broken. We are rendering `false as ""` and `true as "true"`. Quoting from the [HTML5 spec](https://www.w3.org/TR/html5/infrastructure.html#boolean-attributes): "A number of attributes are boolean attributes. The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value."
The handling of boolean attributes was changed in the release `0.7.0` of snabbdom: https://github.com/snabbdom/snabbdom/releases/tag/v0.7.0. Previously it relied on an internal list of boolean attributes and would handle it depending on the attribute name. Now it relies on the type of the value, i.e., if the value is strictly equal to true/false, it will be handled as a boolean …
=> handle boolean attributes with snabbdom

build.sbt, src/main/scala/outwatch/Sink.scala, src/main/scala/outwatch/dom/Handlers.scala, src/main/scala/outwatch/dom/Tags.scala, src/main/scala/outwatch/dom/VDomModifier.scala, src/main/scala/outwatch/dom/helpers/Builder.scala, src/main/scala/outwatch/dom/helpers/DomUtils.scala, src/main/scala/outwatch/dom/helpers/EmitterBuilder.scala, src/main/scala/outwatch/dom/package.scala, src/main/scala/outwatch/http/Http.scala, src/main/scala/outwatch/util/Store.scala, src/main/scala/outwatch/util/SyntaxSugar.scala, src/test/scala/outwatch/AttributeSpec.scala, src/test/scala/outwatch/DomEventSpec.scala, src/test/scala/outwatch/LifecycleHookSpec.scala, src/test/scala/outwatch/OutWatchDomSpec.scala, src/test/scala/outwatch/ScenarioTestSpec.scala, src/test/scala/outwatch/SnabbdomSpec.scala
I refactored the referential transparent API proposed in #68 so that it keeps the client code mostly unchanged (similarly to what the current master API does) but without wrapping the IO monad.
=> Another referential transparent API refactoring

src/main/scala/outwatch/dom/Attributes.scala, src/main/scala/outwatch/dom/VDomModifier.scala, src/main/scala/outwatch/dom/helpers/Builder.scala, src/main/scala/outwatch/dom/helpers/DomUtils.scala, src/main/scala/outwatch/dom/helpers/EmitterBuilder.scala, src/main/scala/snabbdom/VDomProxy.scala, src/test/scala/outwatch/DomEventSpec.scala, src/test/scala/outwatch/OutWatchDomSpec.scala
I made `EmitterBuilder` simpler and at the same time more powerful (arbitrarily composable). This allowed me to remove many helper classes like `GenericMappedEmitterBuilder`, `StringEventEmitterBuilder` and `StringEventEmitter` (+ similar ones).
One thing I was not able to resolve yet: More possibilities made the type inference a bit worse, for example:
```scala
button(inputString(_ => number) --> stream), // _ cannot be inferred anymore,
// since arbitrary values are allowed, so the compiler does not know if you want
// to emit a function or transform the event. Therefore you have to write:
button(inputString((_:String) => number) --> stream),
```
Any ideas on the type inference? We could insert values like `inputString.as(number)`.
=> Refactor EmitterBuilder

src/main/scala/outwatch/dom/VDomModifier.scala, src/main/scala/outwatch/dom/helpers/DomUtils.scala, src/main/scala/outwatch/dom/package.scala, src/test/scala/outwatch/OutWatchDomSpec.scala
In some situations I find it useful to have a composite VDomModifier to be able to easily add multiple `VDomModifiers` to a `VNode`. 
In most cases using the varargs `:_*` syntax works fine, but there are cases where a composite `VDomModifier` is useful. For example, consider the case of some component accepting a label as argument. Normally, one would pass in a string `VNode`, but with a composite `VDomModifier` it would be possible to pass in a string `VNode` plus some additional modifiers to apply (change the class of the component containing the label for example).
=> Adding Composite VDomModifier

src/main/scala/outwatch/VNodeRender.scala, src/main/scala/outwatch/dom/helpers/Builder.scala, src/main/scala/outwatch/dom/package.scala, src/test/scala/outwatch/LifecycleHookSpec.scala
The `ChildStreamReceiverBuilder` accepts `Observable[Any]` which removes type safety and introduces runtime suprises. By accident I can easily write Options, Futures, or other undesired things into the value. This feels like the java-inherited `+` and `any2stringadd` in scala.
I have changed the Builder to only accept types that have an implicit conversion defined. Currently, only strings are automatically converted to `VNode`. So some tests fail as they require `Int` to work, too. Should we define an implicit for primitive types or require an explicit `toString` or what do you expect?
=> build ChildStreamReceiver only from VNodes

build.sbt
we can remove this, because we do not have a main function.
=> disable scalaJSUseMainModuleInitializer option in build.sbt

src/main/scala/outwatch/dom/Compat.scala, src/main/scala/outwatch/dom/VDomModifier.scala, src/main/scala/outwatch/dom/helpers/DomUtils.scala, src/test/scala/outwatch/OutWatchDomSpec.scala
I noticed that when writing
```scala
val vNode = div(
"A",
child <-- messagesA,
"B",
child <-- messagesB
)
```
The order of the children is incorrect. You get `ABxx` instead. I already wrote tests, but don't have an idea for a fix yet.
The tests fail with:
```
[info] - should render child nodes in correct order *** FAILED ***
[info]   "...<span>A</span><span>[B</span><span>1]</span><span>2</span..." was not equal to "...<span>A</span><span>[1</span><span>B]</span><span>2</span..." (OutWatchDomSpec.scala:337)
[info] - should render child string-nodes in correct order *** FAILED ***
[info]   "<div>A[B1]2</div>" was not equal to "<div>A[1B]2</div>" (OutWatchDomSpec.scala:357)
```
=> Incorrect child order

build.sbt, project/plugins.sbt
I saw this interesting snippet in [build.sbt](https://github.com/lihaoyi/scala.rx/blob/master/build.sbt#L57) and thought , that it might be useful for debugging. But I wasn't able to verify that its working.
=> Link source maps to raw.githubusercontent.com

src/main/resources/snabbdom-custom-props.js, src/main/scala/snabbdom/h.scala, src/test/scala/outwatch/DomEventSpec.scala
As discussed in #105, this adds a custom snabbdom props module, which compares against the actual element property.
**Please do not merge**, as I think, the generated code for scala-js is not as performant as a pure javascript implementation. So, we should implement this module in js and somehow include it with scalajs-bundler/webpack.
What do you think?
=> custom snabbdom props module

src/main/scala/outwatch/dom/VDomModifier.scala, src/main/scala/outwatch/dom/helpers/Builder.scala, src/main/scala/outwatch/dom/helpers/DomUtils.scala, src/main/scala/snabbdom/hFunction.scala, src/test/scala/outwatch/LifecycleHookSpec.scala, src/test/scala/outwatch/OutWatchDomSpec.scala, src/test/scala/outwatch/SnabbdomSpec.scala
This PR fixes an issue that caused static nodes to be destroyed/re-inserted when the first `child`/`children` element was emitted.
It also ensures that no `Seq.empty[VNode]` is emitted at the beginning of the `children` stream  when a single `children` stream is present in the node (the common case).
=> Child/children node streams optimisations 

src/main/scala/outwatch/dom/OutwatchAttributes.scala, src/main/scala/outwatch/dom/VDomModifier.scala, src/main/scala/outwatch/dom/helpers/DomUtils.scala, src/main/scala/outwatch/dom/helpers/EmitterBuilder.scala, src/main/scala/snabbdom/hFunction.scala, src/test/scala/outwatch/LifecycleHookSpec.scala, src/test/scala/outwatch/OutWatchDomSpec.scala
Currently, even if there are no hook sinks present on a `VNode`, there are empty insert/update/create hooks created for all the `VNode`s. This PR leaves the hooks as `undefined` in case there are no hook sinks present.
The PR also adds support for the `prepatch`/`postpatch` hooks. I needed `postpatch` for frameworks such [Material Design Lite](https://getmdl.io/) and [Materialize](http://materializecss.com/) that require dynamic components to be "upgraded" after they are inserted in the DOM (using the `update` hooks did not work, the "upgrading" has to happen after the snabbdom patch is completed).
=> Hooks optimisations and refactorings

src/test/scala/outwatch/DomEventSpec.scala, src/test/scala/outwatch/HandlerSpec.scala, src/test/scala/outwatch/JSDomSpec.scala, src/test/scala/outwatch/LifecycleHookSpec.scala, src/test/scala/outwatch/OutWatchDomSpec.scala, src/test/scala/outwatch/ScenarioTestSpec.scala, src/test/scala/outwatch/SnabbdomSpec.scala
The problem was that dom nodes of previous tests leaked into later tests. This was problematic if the previous test used the same id, in this case `id="btn"`. The nondeterminism came from the nondeterministic test execution order. Some test classes didn't clean up the dom which was problematic, if executed in a certain order.
fixes #59
=> Fix cleanup of jsdom environment

build.sbt, src/main/scala/outwatch/Handler.scala, src/main/scala/outwatch/Pipe.scala, src/main/scala/outwatch/Sink.scala, src/main/scala/outwatch/dom/Compat.scala, src/main/scala/outwatch/dom/DomTypes.scala, src/main/scala/outwatch/dom/OutWatch.scala, src/main/scala/outwatch/dom/VDomModifier.scala, src/main/scala/outwatch/dom/helpers/Builder.scala, src/main/scala/outwatch/dom/helpers/DomUtils.scala, src/main/scala/outwatch/dom/helpers/EmitterBuilder.scala, src/main/scala/outwatch/dom/helpers/Snabbdom.scala, src/main/scala/outwatch/dom/package.scala, src/main/scala/outwatch/http/Http.scala, src/main/scala/outwatch/package.scala, src/main/scala/outwatch/util/LocalStorage.scala, src/main/scala/outwatch/util/Store.scala, src/main/scala/outwatch/util/SyntaxSugar.scala, src/main/scala/outwatch/util/WebSocket.scala, src/test/scala/outwatch/AttributeSpec.scala, src/test/scala/outwatch/DomEventSpec.scala, src/test/scala/outwatch/HandlerSpec.scala, src/test/scala/outwatch/JSDomSpec.scala, src/test/scala/outwatch/LifecycleHookSpec.scala, src/test/scala/outwatch/OutWatchDomSpec.scala, src/test/scala/outwatch/ScenarioTestSpec.scala, src/test/scala/outwatch/UnitSpec.scala
This is a port of Outwatch to the [Monix](https://monix.io/) library.
=> Monix port

src/main/scala/outwatch/dom/Compat.scala, src/main/scala/outwatch/dom/DomTypes.scala, src/main/scala/outwatch/dom/Implicits.scala, src/main/scala/outwatch/dom/OutwatchAttributes.scala, src/main/scala/outwatch/dom/dsl.scala, src/main/scala/outwatch/dom/package.scala, src/test/scala/outwatch/AttributeSpec.scala, src/test/scala/outwatch/DomEventSpec.scala, src/test/scala/outwatch/LifecycleHookSpec.scala, src/test/scala/outwatch/OutWatchDomSpec.scala, src/test/scala/outwatch/ScenarioTestSpec.scala, src/test/scala/outwatch/SnabbdomSpec.scala
I did some refactoring to make the DOM DSL imports more consistent and work better with IDE auto-completion.
To import all the DOM DSL identifiers (except for `TagsExtra` and `StylesExtra`) the following import needs to be used:
```
import outwatch.dom.dsl._
```
It's also possible to import just parts of the DSL, and IDE auto-completion helps with this:
```scala
import outwatch.dom.dsl.tags._
import outwatch.dom.dsl.attributes._
import outwatch.dom.dsl.styles._
```
This also addresses #124 by removing `Attributes` and `Tags` from the `outwatch.dom` namespace. Most existing code bases that use `import outwatch.dom._` can be upgraded with:
```bash
find src -name '*.scala' | xargs sed -i -e 's/^\([ \t]*\)import outwatch.dom._/\1import outwatch.dom._\n\1import outwatch.dom.dsl._/'
```
This PR …
=> DOM dsl refactor

src/main/scala/outwatch/dom/Compat.scala, src/main/scala/outwatch/dom/DomTypes.scala, src/main/scala/outwatch/dom/VDomModifier.scala, src/main/scala/outwatch/dom/helpers/Builder.scala, src/main/scala/outwatch/dom/helpers/Snabbdom.scala, src/test/scala/outwatch/AttributeSpec.scala, src/test/scala/outwatch/OutWatchDomSpec.scala
This PR adds support for attributes that can be accumulated within the same `VNode`, in particular for accumulating `className`s within a `VNode`.
I often find this useful when I'm using some component and I want to pass in some additional `className` modifier to the component without overriding the class(es) that the component already uses.
For example:
```scala
def component(modifiers: VDomModifier*): VNode
val disabled = classAccum := "disabled-class"
if (someCondition) component(modifiers: _*) else component( (disabled +: modifiers) : _*)
```
=> Add support for accumulated attributes (className in particular)

src/main/scala/outwatch/dom/helpers/DomUtils.scala, src/test/scala/outwatch/OutWatchDomSpec.scala
Fixes a bug when there are multiple child nodes and only one emits.
On top of #130.
=> Multiple child node fix

src/main/scala/outwatch/dom/DomTypes.scala, src/main/scala/outwatch/dom/Implicits.scala, src/main/scala/outwatch/dom/OutwatchAttributes.scala, src/main/scala/outwatch/dom/VDomModifier.scala, src/main/scala/outwatch/dom/helpers/Builder.scala, src/main/scala/outwatch/dom/helpers/DomUtils.scala, src/main/scala/outwatch/dom/helpers/Snabbdom.scala, src/main/scala/snabbdom/hFunction.scala, src/test/scala/outwatch/AttributeSpec.scala, src/test/scala/outwatch/OutWatchDomSpec.scala
This PR adds support for the Snabbdom [`delayed`, `remove` and `destroy` styles](https://github.com/snabbdom/snabbdom#delayed-properties) which allow for easy CSS animations. It also adds support for accumulating styles in order to be able to write composable animations like so:
```scala
val slideInOut = VDomModifier(
transition.accum := "transform .2s ease-in-out",
transform := "translateX(-50px)",
transform.delayed := "translateX(0px)",
transform.remove := "translateX(50px)",
)
val fadeInOut = VDomModifier(
transition.accum :=  "opacity .2s ease-in-out",
opacity := 0,
opacity.delayed := 1,
opacity.remove := 0
)
val moveInOut =  VDomModifier(slideInOut, fadeInOut)
```
You can see this animation in action [here](https://mariusmuja.github.io/outwatch-demo-spa/#todo) when adding or removing …
=> Extended styles

src/main/scala/outwatch/Sink.scala, src/test/scala/outwatch/HandlerSpec.scala
Another controversial feature! 😆 
I'm interfacing a lot with `d3`, so this and #146 are important to me. Implementing this function directly on `Sink` is way more efficient than implementing it using `unsafeSink` from #76.
=> Add unsafeOnNext to Sink

src/main/scala/outwatch/SideEffects.scala, src/main/scala/outwatch/dom/package.scala, src/test/scala/outwatch/DomEventSpec.scala
One can now write things like:
```scala
button(
onClick --> (event => handleEvent(event)),
onClick(1) --> (counter += _),
onClick --> (() => counter += 1),
)
```
=> Emitter accept side-effecting functions

src/main/scala/outwatch/dom/Compat.scala, src/main/scala/outwatch/dom/OutwatchAttributes.scala, src/main/scala/outwatch/dom/helpers/EmitterBuilder.scala, src/main/scala/outwatch/dom/helpers/TargetOps.scala, src/test/scala/outwatch/DomEventSpec.scala, src/test/scala/outwatch/ScenarioTestSpec.scala
This PR is a result of the discussion we had in https://github.com/OutWatch/outwatch/pull/119#issuecomment-351861345. It still uses the non-typesafe cast for `currentTarget`, but allows for a nicer syntax and uses the `TagWith...` typeclasses for restricting the type the target can be cast to.
The syntax is the following:
* `currentTarget` uses `html.Input` by default as the underlying event target:
```scala
input(
onInput.value --> string,
onClick.checked --> bool,
onKeyDown.valueAsNumber --> number
)
```
The PR removes `onInputString`, `onInputNumber` and `onInputChecked` and updates the deprecation message on `inputString`, `inputNumber` and `inputChecked` to use  `onInput.value`, `onInput.valueAsNumber` and `onChange.checked` instead.
*  it's possible to force a different event target …
=> CurrentTarget / Target ops

src/main/scala/outwatch/dom/Compat.scala, src/main/scala/outwatch/dom/OutwatchAttributes.scala, src/test/scala/outwatch/LifecycleHookSpec.scala
This makes it more consistent with all the other camel-case identifiers.
=> Rename on{Pre,Post}patch to on{Pre,Post}Patch

src/main/scala/outwatch/dom/DomTypes.scala, src/main/scala/outwatch/dom/OutwatchAttributes.scala, src/main/scala/outwatch/dom/helpers/EmitterBuilder.scala, src/main/scala/outwatch/dom/helpers/TargetOps.scala, src/test/scala/outwatch/LifecycleHookSpec.scala
Makes `Hooks` and `EmitterBuilder` consistent, closes #152.
=> Make Hooks and EmitterBuilder consistent

src/main/scala/outwatch/Sink.scala, src/main/scala/outwatch/dom/DomTypes.scala, src/main/scala/outwatch/dom/OutWatch.scala, src/main/scala/outwatch/dom/OutwatchAttributes.scala, src/main/scala/outwatch/dom/VDomModifier.scala, src/main/scala/outwatch/dom/helpers/Builder.scala, src/main/scala/outwatch/dom/helpers/DomUtils.scala, src/main/scala/outwatch/dom/helpers/EmitterBuilder.scala, src/main/scala/outwatch/dom/helpers/Snabbdom.scala, src/main/scala/outwatch/dom/package.scala, src/main/scala/outwatch/http/Http.scala, src/main/scala/outwatch/util/WebSocket.scala, src/test/scala/outwatch/AttributeSpec.scala, src/test/scala/outwatch/OutWatchDomSpec.scala
This PR consists only of proposed renames and small code shuffles.
* it renames builders in  `Builder.scala` to make them more consistent with the names of the attributes they are building
* renames `VDomModifier_` to `Modifier`
* renames `StaticVNode.asProxy` to `StaticVNode.toSnabbdom`
* re-arranges code in `DomTypes`
Because of so many renames, this PR has a high likelihood of generating conflicts, so it should maybe be left until the other PRs get merged first.
=> Renames / Refactorings

src/main/scala/outwatch/SideEffects.scala, src/main/scala/outwatch/Sink.scala, src/main/scala/outwatch/dom/ManagedSubscriptions.scala, src/main/scala/outwatch/util/WebSocket.scala, src/test/scala/outwatch/LifecycleHookSpec.scala, src/test/scala/outwatch/OutWatchDomSpec.scala
There is no need for `Sink.create` arguments functions to return `IO`s. Any side-effects that these functions might perform are suspended in the closures.
=> No need for Sink.create arguments functions to return IO

src/main/scala/outwatch/SideEffects.scala, src/main/scala/outwatch/Sink.scala, src/main/scala/outwatch/dom/ManagedSubscriptions.scala, src/main/scala/outwatch/util/WebSocket.scala, src/test/scala/outwatch/LifecycleHookSpec.scala, src/test/scala/outwatch/OutWatchDomSpec.scala
Wrap `Sink.create` in `IO`. Fixes #81.
On top of #164.
=> Wrap Sink.create in IO

src/main/scala/outwatch/dom/VDomModifier.scala, src/main/scala/outwatch/dom/helpers/DomUtils.scala, src/main/scala/outwatch/dom/helpers/Snabbdom.scala, src/test/scala/outwatch/DomEventSpec.scala, src/test/scala/outwatch/JSDomSpec.scala, src/test/scala/outwatch/OutWatchDomSpec.scala, src/test/scala/outwatch/ScenarioTestSpec.scala
This PR refactors the way the VNode observables are combined, using `merge` & `scan` (and explicit VNode state) instead of `combineLatest`.
I think it makes the code simpler and removes the need for workarounds such as keeping track if there's one or more child observables or making sure there's a `startWith` on the streams for partial rendering, avoiding issues such as #137, #134.
=> Combine observables using merge/scan

src/main/scala/outwatch/dom/DomTypes.scala
Currently the domtypes tag builder creates a `VNode` which results in each `VNode` with arguments in the VDOM DSL making use of the `ioVTreeMerge` implicit conversion. 
This patch changes the domtypes tag builder to create a `VTree` instead, so there is no implicit conversion needed in most case.
It has the downside(?) that empty tags need to have empty argument lists, so `div` is not valid as an empty tag in the VDOM, it needs to be `div()`.
=> Have TagBuilder create VTree instead of VNode

src/main/scala/outwatch/AsVDomModifier.scala, src/main/scala/outwatch/StaticVNodeRender.scala, src/main/scala/outwatch/dom/Compat.scala, src/main/scala/outwatch/dom/DomTypes.scala, src/main/scala/outwatch/dom/OutwatchAttributes.scala, src/main/scala/outwatch/dom/helpers/Snabbdom.scala, src/test/scala/outwatch/DomEventSpec.scala, src/test/scala/outwatch/LifecycleHookSpec.scala, src/test/scala/outwatch/OutWatchDomSpec.scala, src/test/scala/outwatch/ScenarioTestSpec.scala, src/test/scala/outwatch/SnabbdomSpec.scala
Keeps, but deprecates `child <--` and `children <--`.
Closes #169.
=> AsVDomModifier typeclass support for Observable and Observable[Seq]

src/main/scala/outwatch/util/Store.scala
Fixes #174.
When `.startWith()` comes before `.share`, only the first subscription receives the initial element. This cases problems because every a `store.sink.redirect()` (usually called in most EmitterBuilders) creates a subscription.
=> Use .startWith() after .share on Store

src/main/scala/outwatch/Sink.scala, src/main/scala/outwatch/dom/helpers/EmitterBuilder.scala, src/main/scala/outwatch/util/Store.scala
Add `Sink.unsafeRedirect` and use it in `EmitterBuilder`. VDom streams are infinite (don't complete), so the extra checks in Sink.redirect are not needed in this case.
The safer `Sink.redirect` is useful for uses of `Sink` that can complete, such as in `Http`, `WebSocket`.
On top of #175.
=> Add Sink.unsafeRedirect

src/main/scala/outwatch/dom/OutWatch.scala, src/main/scala/outwatch/util/Store.scala, src/test/scala/outwatch/ScenarioTestSpec.scala
This PR contains several refactorings/improvements to `Store`:
* removes the `Store` class and makes the Store just a `Pipe[Action, State]`
* changes default reducer signature to `(State, Action) => (State, Observable[Action])`, instead of `(State, Action) => (State, Option[IO[Action]])`, which I think is more clear, easier to use and more flexible (allows for more than one effect to be potentially emitted).
* it's possible to use reducers without effects  `(State, Action) => State` and also in the previous form `(State, Action) => (State, Option[IO[Action]])`
* added `Store.create` which can be used to create local stores, without the need to use `renderWithStore`
* uses `observer.feed` instead of `observer.onNext`, so that the store behaves correctly in case an effect is emitted …
=> Store improvements

src/main/scala/outwatch/util/LocalStorage.scala
Instead of getting a handler with my own events and the events of other browser windows, I need to have a handler with only storage events from other windows (dropping events coming from my actions).
This introduces `Storage.handlerWithEventsOnly` to do just that.
=> add Storage.handlerWithEventsOnly for only getting storage events

build.sbt, src/main/scala/outwatch/dom/DomTypes.scala, src/main/scala/outwatch/dom/dsl.scala, src/test/scala/outwatch/AttributeSpec.scala, src/test/scala/outwatch/DomEventSpec.scala
Uses current jitpack snapshot of scala-dom-types to support svg tags and attributes.
=> support svg

src/main/scala/outwatch/dom/helpers/EmitterOps.scala, src/test/scala/outwatch/DomEventSpec.scala
helper methods for calling functions on event when using an EmitterBuilder. Works for: preventDefault, stopPropagation, stopImmediatePropagation
=> event actions on EmitterBuilder

README.md
I believe that a lot of newcomers still start using the outdated outwatch version `0.10.x`. They should use the new one instead.
fixes #84, #46
=> Stop advertising old Outwatch version

src/main/scala/outwatch/dom/helpers/Snabbdom.scala
When there is an update to a stream receiver from a VNode, we create a new VNodeProxy for it. Previously we always calculated the Receivers on each update, but this is not necessary: Updates come from the initially created Receivers and only contain static Modifiers. Therefore, there is no need to try finding a stream in these static modifiers.
based on #204
=> do not calculate receivers on update

src/main/scala/outwatch/dom/helpers/Snabbdom.scala
Fix merging hooks in `updateDataObject`, we should not replace them but merge with the ones from the proxy (as with everything else).
Based on #208
=> merge hooks correctly on update

build.sbt, src/main/scala/outwatch/Handler.scala, src/main/scala/outwatch/dom/DomTypes.scala, src/main/scala/outwatch/dom/dsl.scala, src/test/scala/outwatch/AttributeSpec.scala
The update introduces a new API which makes it impossible for now to separate attributes and reflected attributes. Our `Dsl` supported this with `outwatch.dom.dsl.attributes.attrs._`,  `outwatch.dom.dsl.attributes.reflected._` and  `outwatch.dom.dsl.attributes.props._`. I have now changed this to have `outwatch.dom.dsl.attributes.attrs._` contain all three (attributes, reflected attributes, properties). I think, this should be fine because I do not really see the use-case for such fine-granular import separation.
=> Update scala-dom-types to v0.9

CHANGELOG.md, build.sbt, src/main/scala/outwatch/AsVDomModifier.scala, src/main/scala/outwatch/Handler.scala, src/main/scala/outwatch/MonixOps.scala, src/main/scala/outwatch/dom/AsObserver.scala, src/main/scala/outwatch/dom/AsValueObservable.scala, src/main/scala/outwatch/dom/Compat.scala, src/main/scala/outwatch/dom/Implicits.scala, src/main/scala/outwatch/dom/ManagedSubscriptions.scala, src/main/scala/outwatch/dom/OutwatchAttributes.scala, src/main/scala/outwatch/dom/VDomModifier.scala, src/main/scala/outwatch/dom/ValueObservable.scala, src/main/scala/outwatch/dom/helpers/Builder.scala, src/main/scala/outwatch/dom/helpers/DomUtils.scala, src/main/scala/outwatch/dom/helpers/EmitterBuilder.scala, src/main/scala/outwatch/dom/helpers/QueuedCancelable.scala, src/main/scala/outwatch/dom/helpers/Snabbdom.scala, src/main/scala/outwatch/dom/package.scala, src/main/scala/outwatch/util/SyntaxSugar.scala, src/main/scala/snabbdom/hFunction.scala, src/test/scala/outwatch/DomEventSpec.scala, src/test/scala/outwatch/LifecycleHookSpec.scala, src/test/scala/outwatch/OutWatchDomSpec.scala, src/test/scala/outwatch/SnabbdomSpec.scala
This PR has become quite the collection of changes which we did when working on our application. When investigating performance issues, we saw that the number of snabbdom patches needed to render our initial page was really high (multiple hundred times depending on the number of items displayed). Furthermore, updates on small subcomponents were triggering multiple times.
When using a stream of VDomModifier, outwatch would always render the element with an `empty placeholder` first, and then apply updates in form of snabbdom patches. In our case, we always have a `current value` (because our state is modeled with scalarx, same holds if you are using monix Var). Therefore, we know that we are able to render our initial page without any patching, because we know the initial state.
This lead …
=> Modifier stream with value

build.sbt
Fixes an incompatibility between cats-effect `1.0.0` and monix `3.0-RC1`, as reported by @ahjohannessen via gitter. We need to wait for monix `RC2` to upgrade.
=> downgrade cats-effect back to 0.10.1

bench/src/main/scala/Performance.scala
Otherwise the benchmarks are not reliably measuring the right thing because patching is scheduled async.
=> use trampoline scheduler in benchmark

outwatch/src/main/scala/outwatch/dom/helpers/Snabbdom.scala
Provides a way to get events about exceptions being thrown in your observable modifiers. You can trace them via `OutwatchTracing.error`. Maybe we should have a way to handle error with a PartialFunction. But this is a first step.
In an application, we use it to show an error page, because something is going wrong. As of now, we do not know what but that is better than nothing -- and definitely better than let the user wonder why some parts do not work anymore.
We can think of extending this and have a way to handle this per `VNode`. So you could define different error handling strategies: (1) just fail and log like now, (2) notify the application about an error and stop, (3) just continue and swallow the exception.
_Oh, maybe we should rename OutwatchTracing to camel-case OutWatchTracing …
=> add OutwatchTracing.error for detecting patching errors

outwatch/src/test/scala/outwatch/LifecycleHookSpec.scala
We had a blind eye on the LifecycleHooks, because the spec was never run. I do not know, why scalatest compiles in a sync test suite, when we just return `IO[Assertion]`, but it did and never ran our assertions.
This PR make LifecycleHookSpec extend `JsDomAsyncSpec` which will take care of running our IO in a future. It additionally fixes all the failing tests, nothing problematic but we just need to have a key if we want to test snabbdom hooks properly.
=> fix LifeCycleHookSpec

outwatch/src/main/scala/outwatch/dom/helpers/DomUtils.scala, outwatch/src/test/scala/outwatch/LifecycleHookSpec.scala
The logic of streamed unmount hooks has a flaw. It uses `PostPatchHooks` which are not guaranteed to be run before all mount hooks of the next patch-iteration. This PR now uses `UpdateHook` for mirroring streamed unmount hooks. This will always be done before any mount hook which is called from an insert or post patch hook. And importantly it also needs to be done after the `PrePatchHooks` because of thunks and because prepatch can be called more often than update by snabbdom.
Based on #273
=> fix wrong order of mount and unmount when streamed

outwatch/src/main/scala/outwatch/dom/OutWatch.scala, outwatch/src/main/scala/snabbdom/hFunction.scala
This is replacing the custom approach with the correct one. Before, renderReplace kept the attributes of the tag. Now the whole tag will be replaced correctly.
=> Use snabbdom/tovnode for renderReplace

outwatch/src/main/scala/outwatch/dom/ChildCommand.scala, outwatch/src/test/scala/outwatch/OutWatchDomSpec.scala
We currently have `outwatch.dom.ChildId` defined for ChildCommands, which will be imported in many applications using outwatch (`import outwatch.dom._`). It occupies a very generic name, but it has a very specific usecase only for ChildCommands.
So, I have moved the `ChildId` type to the ChildCommand object.
=> remove ChildCommand's ChildId from dom package namespace

outwatch/src/main/scala/outwatch/dom/OutWatch.scala, outwatch/src/main/scala/outwatch/util/Store.scala, outwatch/src/test/scala/outwatch/ScenarioTestSpec.scala, outwatch/src/test/scala/outwatch/StoreSpec.scala
This PR makes the following changes to `Store` (in order of significance)
* Makes Store emit an (action -> state) tuple.
* This tuple allows more granular control about *when* a view updates when the stores state changes.  
Methods like `collect` can now be used to, not only capture certain state changes, but they can also react to the `Action` which caused that state.  
This allows us to ignore all other Actions which are irrelevant to that specific view.  
For example, if we were to move a draggable element using a mouse cursor, we could react just to events changing the position of the element, while discarding all other state updates.
```scala
svg(
rect(width := 10, height := 10,
x <-- store.collect { case (MoveAction, state) => state.xPos },
y <-- store.collect { case (MoveAction, …
```
=> Multiple changes to Store

build.sbt, project/plugins.sbt
Notify me if there is anything I missed.  
Since the lib does not contain any custom collection implementations, staying on `2.12` for the build should be fine.
=> Make outwatch work with scala 2.13

bench/yarn.lock, build.sbt, outwatch/yarn.lock
Use semantic versioning for snabbdom npm dependency by using `<git-url>#semver:<version-tag>`, which enforces semantic versioning and fixes problems when having a version conflict for snabbdom. Can happen if you use a third-party library, which depends on another version of outwatch than you are.
fixes #297
=> depend on snabbdom with semantic versioning

outwatch/src/main/scala/outwatch/dom/VDomModifier.scala, outwatch/src/test/scala/outwatch/OutWatchDomSpec.scala
We have `thunk`, `thunkConditional` and `thunkStatic`. This PR renames `conditional` and `static` methods to make more clear that these methods are using thunks as well.
* `thunk(key)(dependencies*)(modifier)`
* `conditional` -> `thunkConditional(key)(shouldRender)(modifier)`
* `static` -> `thunkStatic(key)(modifier)`
=> Rename thunk methods

outwatch/src/main/scala/outwatch/dom/helpers/EmitterBuilder.scala
This makes EmitterBuilders more useful. You can have an `EmitterBuilder[X, VNode]` via `EmitterBuilder.ofNode`. For VDomModifier, you can still use `EmitterBuilder.ofModifier`. Additionally, you may map over the result of an `EmitterBuilder` via `mapEmitter`.
~~We are restricting the EmitterBuilders to these two types, because we might need to handle a monix subscription when using observable-based EmitterBuilder transformations. And we can nicely handle these subscriptions for Nodes and Modifiers by using lifetime hooks. We could probably add another `EmitterBuilder.custom` method to have any type while handling the subscription yourself. But I am not sure whether this is really needed, because EmitterBuilders are usually used for Modifiers.~~
Update: I have added …
=> add EmitterBuilder.ofNode and mapEmitter

outwatch/src/main/scala/outwatch/dom/helpers/Snabbdom.scala
Adds an `asyncBoundary` in each Observable of a VNode just before patching. Performance seems to be much better, because we leave room for events to be handled in between patching and do not back-pressure the times it takes to patch a VNode.
=> AsyncBoundary before patch

bench/src/main/scala/Performance.scala, outwatch/src/main/scala/outwatch/dom/OutwatchAttributes.scala, outwatch/src/main/scala/outwatch/dom/helpers/EmitterBuilder.scala, outwatch/src/main/scala/outwatch/dom/helpers/Snabbdom.scala, outwatch/src/main/scala/outwatch/util/Store.scala, outwatch/src/test/scala/outwatch/LifecycleHookSpec.scala, outwatch/src/test/scala/outwatch/OutWatchDomSpec.scala, outwatch/src/test/scala/outwatch/OutwatchSpec.scala, outwatch/src/test/scala/outwatch/ScenarioTestSpec.scala
Most of these warnings are monix deprecation warnings brought in by #320 
A couple of them are a little suspect, as they appeared as discarded non-unit value warnings:
```scala
object EmitterBuilder {
@inline def apply[E <: Event](eventType: String): CustomEmitterBuilder[E, VDomModifier] = ofModifier[E](obs => 
Emitter(
eventType, 
event => {
obs.onNext(event.asInstanceOf[E])
()
}))
```
`onNext` creates a future, but I don't see any way that this future is waited on, as it's not returned or awaited.  Not suggesting it should be awaited here, just unclear to me how this sideeffect is ok in this context.
Below are a bunch of warnings that have been fixed:
```scala
sbt:OutWatch> test
[info] Updating ...
[info] Done updating.
[warn] There may be incompatibilities among your library …
```
=> Fix warnings

outwatch/src/main/scala/outwatch/util/Store.scala, outwatch/src/test/scala/outwatch/ScenarioTestSpec.scala, outwatch/src/test/scala/outwatch/StoreSpec.scala
The use of Try / catchNonFatal / recover / get, is basically
a debug println. Here I simply remove this usage, and allow
the MonadError[F, Throwable] of Sync[F] to handle any thrown
exceptions.
I think the intention of the deleted code is primarily to log exceptions thrown by the passed reducer. This is the responsibility of the caller/creator of the store, and thus should be handled if necessary by the caller.
=> Remove impurity around creation of a store

build.sbt, outwatch/src/main/scala/outwatch/MonixOps.scala, outwatch/src/main/scala/outwatch/dom/helpers/DomUtils.scala, outwatch/src/main/scala/outwatch/dom/helpers/NativeHelpers.scala, outwatch/src/main/scala/outwatch/dom/helpers/Snabbdom.scala, outwatch/src/main/scala/outwatch/http/Http.scala, outwatch/src/main/scala/outwatch/util/LocalStorage.scala, outwatch/src/main/scala/outwatch/util/WebSocket.scala, outwatch/src/main/scala/snabbdom/hFunction.scala, outwatch/src/test/scala/outwatch/DomEventSpec.scala, outwatch/src/test/scala/outwatch/OutWatchDomSpec.scala, outwatch/src/test/scala/outwatch/StoreSpec.scala, project/Options.scala
```
[error] /home/projects/oss/outwatch/outwatch/src/main/scala/outwatch/dom/helpers/NativeHelpers.scala:9:13: parameter value key in method apply is never used
[error]   def apply(key: String): js.UndefOr[A] = js.native
[error]             ^
[error] /home/projects/oss/outwatch/outwatch/src/main/scala/outwatch/dom/helpers/Snabbdom.scala:40:148: parameter value scheduler in method createProxy is never used
[error]   @inline private def createProxy(modifiers: SeparatedModifiers, nodeType: String, vNodeId: js.UndefOr[Int], vNodeNS: js.UndefOr[String])(implicit scheduler: Scheduler): VNodeProxy = {
[error]                                                                                                                                                    ^
[error] …
```
=> Fix more unused parameter warnings

build.sbt
The current master mistakenly publishes the bench project, such that our jitpack dependencies break (because there are now multiple artifacts for outwatch in jitpack).
Thanks to @Busti for pointing this out!
=> Really skip publishing bench project

bench/yarn.lock, build.sbt, outwatch/src/main/scala/snabbdom/Snabbdom.scala, tests/src/test/scala/outwatch/OutWatchDomSpec.scala, tests/src/test/scala/outwatch/SnabbdomSpec.scala
And update snabbdom fork to 0.7.5. Contains latest changes from snabbdom/snabbdom master-branch and remove parsing of selector tags to find encoded `#id.cls` in selector tags of snabbdom (we do not need this).
I have moved the snabbdom fork to our organization now: So the new dependency is from outwatch/snabbdom. The old dependency will keep on working because of githubs redirections.
Based on #355
=> Remove hfunction from Snabbdom Facade

.travis.yml
Only run travis on jdk11, the tests are run only by node anyways.
=> Only run travis on jdk11

.travis.yml
Travis was running the old version...
=> Travis: use ScalaJS 0.6.32 (like in plugins)

build.sbt, monix/yarn.lock, outwatch/src/main/scala/outwatch/helpers/NativeHelpers.scala, outwatch/src/main/scala/snabbdom/Snabbdom.scala, outwatch/yarn.lock, reactive/yarn.lock, repairdom/src/main/scala/outwatch/repairdom/RepairDom.scala, repairdom/yarn.lock, tests/src/test/scala/outwatch/RepairDomSpec.scala
The goal is to handle externally manipulated dom gracefully. This occurs when using js-libraries which manipulate the dom themselves.
Snabbdom assumes in its [patch operation](https://github.com/snabbdom/snabbdom#patch) that the **virtual dom exactly matches the real dom**. If this is not the case, the patch function might crash.
My idea is to mark the real dom as dirty. Then let outwatch detect dirty dom and repair it before the patch.
Based on #355
=> WIP: repairing dirty dom

outwatch/src/main/scala/outwatch/EmitterBuilder.scala, tests/src/test/scala/outwatch/DomEventSpec.scala
Snabbdom registers only one event listener for each occurring `eventType` in a VNode. This is why, we cannot implement #217 with snabbdom. Multiple handlers, will still yield only one event listener. Then, the dom cannot stop immediate propagation on these handlers.
=> remove stopImmediatePropagation from API (see #217)

build.sbt, project/plugins.sbt
Supersedes https://github.com/outwatch/outwatch/pull/551. This should hopefully get you unblocked while we wait for https://github.com/scalameta/mdoc/pull/597.
=> Update to Scala.js 1.8.0

build.sbt
Follow up to https://github.com/outwatch/outwatch/pull/563#issuecomment-1007982347.
This is ... not nice. I don't think it would be unreasonable to rollback to SJS 1.7 instead. Whatever works for you 👍
=> Fix SJS 1.8 update

build.sbt, project/plugins.sbt
Howdy! 
We've just released 2.3.1 which hopefully addresses the issues seen in #573
Locally I've been able to run `docs/docusaurusCreateSite`, whereas it was crashing before
=> Mdoc 2.3.1, remove no longer necessary hacks

build.sbt, outwatch/src/main/scala/outwatch/helpers/MutableNestedArray.scala, outwatch/src/main/scala/outwatch/interpreter/ModifierToSnabbdom.scala, tests/src/test/scala/outwatch/OutWatchDomSpec.scala
Currently, we setup mount and unmount hooks for every observable we encounter.
But some observables are empty or return just a few values or return a value from unsafely running a SyncIO or IO.
Colibri does not have a direct concept of completion to listen to, but we can check whether `subscribe` returns a Cancelable that is empty - no values coming in anymore and nothing to cancel.
This PR checks for empty subscriptions and ignores them - thereby having less overhead: no mount/unmount hooks, no preparation for patching the dom node.
Based on https://github.com/cornerman/colibri/pull/182
=> optimization: ignore empty subscriptions

outwatch/src/main/scala/outwatch/helpers/MutableNestedArray.scala, outwatch/src/main/scala/outwatch/helpers/NativeHelpers.scala, outwatch/src/main/scala/outwatch/interpreter/ModifierToSnabbdom.scala, outwatch/src/main/scala/outwatch/interpreter/SnabbdomOps.scala, tests/src/test/scala/outwatch/DomEventSpec.scala, tests/src/test/scala/outwatch/LifecycleHookSpec.scala, tests/src/test/scala/outwatch/OutWatchDomSpec.scala, tests/src/test/scala/outwatch/OutwatchSpec.scala, tests/src/test/scala/outwatch/ScenarioTestSpec.scala, tests/src/test/scala/outwatch/SnabbdomSpec.scala
The main change is to move snabbdom patching into a micro task (currently running synchronously). Now it would run async but before any rendering or dom events. See about event loops in javascript: https://javascript.info/event-loop
I owe this idea to @armanbilge. Thank you so much :)
The advantages:
- We will gather all observable triggers (even from nested observables) before the first render -> this circumvents triggering multiple succeeding patch calls inside one transcation.
- Multiple observables inside one node only do one patch call!
- In diamond cases, we will not render invalid state -> no (visible) frp glitches!
- Promise-based modifiers can still be captured inside the initial render and do not need an additional patch.
- When triggering from an emitter builder, we do not …
=> Async patching and batching

outwatch/src/main/scala/outwatch/Render.scala
We cannot assume that a Show instance is always meant to be rendered in the UI.
=> remove Render instances for cats.Show and add Render.show[T]

outwatch/src/main/scala/outwatch/Render.scala, tests/src/test/scala/outwatch/AttributeSpec.scala, tests/src/test/scala/outwatch/OutWatchDomSpec.scala
I am not sure why, but otherwise this implicit instance allows us to render a `()`, which we do not want. So, currently, you always have to convert a `js.UndefOr` with `toOption` to render it.
=> remove js.undefined render instances to not render Unit

outwatch/src/main/scala/outwatch/VMod.scala, outwatch/src/main/scala/outwatch/interpreter/ModifierToSnabbdom.scala, tests/src/test/scala/outwatch/OutWatchDomSpec.scala
Use-case: Catch exception inside a subtree of the virtual dom.
You can now change the `RenderConfig` for a modifier, and thereby also change the `RenderConfig#errorModifier`.
Usage:
```VMod.configured(myModifier)(outsideRenderConfig => outsideRenderConfig.copy(...))```
```VMod.catchError(myModifier)(throwable => div("broken " + throwable))```
=> add ConfiguredModifier to change RenderConfig inside the virtual dom

outwatch/src/main/scala/outwatch/EmitterBuilder.scala
This method name comes from akka-streams. I find it more intuitive than `discard` - to me `discard` sounds like discarding the whole stream. Though, you can also interpret it as discarding the value in the stream. On the other hand, `done` clearly means that you are finished with the processing of the stream.
=> rename EmitterBuilder#discard to EmitterBuilder#done

README.md, docs/readme.md
remove the quickstart guide from the readme, in order to only have one source of truth.
references #760
=> improve getting-started in docs
