src/main/scala/outwatch/dom/helpers/EventEmitterBuilder.scala
src/main/scala/outwatch/dom/package.scala
src/test/scala/outwatch/AttributeSpec.scala

As per http://www.w3schools.com/tags/att_global_data.asp

allow dynamic data attributes

---

src/main/scala/outwatch/dom/package.scala

Fixes https://github.com/OutWatch/outwatch/issues/11

Fix type of `selected` attribute

---

src/main/scala/outwatch/dom/Attributes.scala
src/main/scala/outwatch/dom/Tags.scala
src/main/scala/outwatch/dom/VDomModifier.scala
src/main/scala/outwatch/dom/helpers/Builder.scala
src/main/scala/outwatch/dom/helpers/EmitterBuilder.scala
src/main/scala/snabbdom/VDomProxy.scala

There were a few commits that didn't make it into the previous PR.

#16 The missing parts

---

src/main/scala/outwatch/dom/Attributes.scala
src/main/scala/outwatch/dom/VDomModifier.scala
src/main/scala/outwatch/dom/helpers/EmitterBuilder.scala
src/main/scala/snabbdom/VDomProxy.scala
src/test/scala/outwatch/OutWatchDomSpec.scala

Added option to filter emitted events

---

build.sbt
src/main/scala/outwatch/dom/VDomModifier.scala
src/main/scala/outwatch/dom/helpers/DomUtils.scala
src/main/scala/snabbdom/VDomProxy.scala
src/main/scala/snabbdom/h.scala
src/test/scala/outwatch/AttributeSpec.scala

Hi, we introduced a Style attribute which uses the Style Module of Snabbdom. Is this going in the right direction? Should we make it usable like ScalaTags?

Introduce Style Attribute

---

src/main/scala/outwatch/dom/helpers/Builder.scala

add style builder

---

build.sbt
project/plugins.sbt
src/main/scala/outwatch/Sink.scala
src/main/scala/outwatch/dom/OutWatch.scala
src/main/scala/outwatch/dom/Tags.scala
src/main/scala/outwatch/dom/VDomModifier.scala
src/main/scala/outwatch/dom/helpers/Builder.scala
src/main/scala/outwatch/dom/helpers/DomUtils.scala
src/main/scala/outwatch/dom/helpers/STRef.scala
src/main/scala/outwatch/dom/package.scala
src/main/scala/outwatch/http/Http.scala
src/main/scala/outwatch/util/LocalStorage.scala
src/main/scala/outwatch/util/Store.scala
src/main/scala/outwatch/util/WebSocket.scala
src/main/scala/snabbdom/h.scala
src/test/scala/outwatch/AttributeSpec.scala
src/test/scala/outwatch/DomEventSpec.scala
src/test/scala/outwatch/LifecycleHookSpec.scala
src/test/scala/outwatch/OutWatchDomSpec.scala
src/test/scala/outwatch/ScenarioTestSpec.scala
src/test/scala/outwatch/SnabbdomSpec.scala

First version where all tests pass!
Needs more work on `Store` and the like. For now, though, I'm quite happy how it turned out.
Will also have to update the documentation when this is merged (I'd like to use `tut` in the future for docs) :)

Refactor to referential transparent api

---

build.sbt

In the 2.12.4 update I forgot to update `crossScalaVersions` ...

Update crossScalaVersions to 2.12.4

---

src/main/scala/outwatch/dom/Compat.scala
src/main/scala/outwatch/dom/HandlerFactories.scala

Fix backwards compatibility broken in #91

Fix backwards compatibility

---

build.sbt

remove scalac option -Xcheckinit and update domtypes

---

src/main/scala/outwatch/dom/ManagedSubscriptions.scala
src/main/scala/outwatch/dom/package.scala
src/test/scala/outwatch/LifecycleHookSpec.scala

This implements managed subscriptions as discussed in #121.
Closes #121.

Managed subscriptions

---

build.sbt
src/main/scala/outwatch/dom/helpers/Snabbdom.scala
src/main/scala/outwatch/http/Http.scala

Updated some dependencies:
monix - 3.0.0-M3
cats - 1.0.1
cats-effect - 0.8
snabbdom - 0.7.1

Update dependencies: monix, cats, cats-effect, snabbdom

---

src/main/scala/outwatch/util/LocalStorage.scala
src/test/scala/outwatch/JSDomSpec.scala
src/test/scala/outwatch/OutWatchDomSpec.scala

fixes #157 -- does github break if I do this? 😈 
fixes #77

Implement LocalStorage Handler which reacts on StorageEvent

---

README.md

Luka published RC-2 on maven. I think it's a good time to collect some feedback. For this we should also document the changes since the last release.

Add RC to readme

---

build.sbt

Update to latest releases of cats and cats-effect.

Update cats and cats-effect

---

src/main/scala/outwatch/dom/helpers/Snabbdom.scala
src/main/scala/snabbdom/hFunction.scala

Does this have implications on how the diffing and/or patching is done? I was not really able to tell from the snabbdom docs but was curious whether this makes a difference.

let snabbdom patch return patched node

---

src/main/scala/outwatch/dom/OutWatch.scala
src/test/scala/outwatch/LifecycleHookSpec.scala

use div instead of app as tag for Outwatch.renderInto

---

README.md

I took the time to write some usage examples. There is a lot that is still missing. If someone else has the time to contribute an example, please do.

WIP: Documentation and Examples

---

bench/yarn.lock
build.sbt
outwatch/yarn.lock

Update our fork of snabbdom to the new version 0.7.3 of snabbdom.

update snabbdom to 0.7.3

---

README.md

Seeing as Cats has switched, seems like a good time to follow suit.

Switch to the Scala CoC

---

jitpack.yml

In order to build all scala versions on jitpack.

add jitpack yml to cross-build

---

outwatch/src/main/scala/outwatch/VDomModifier.scala
outwatch/src/main/scala/outwatch/helpers/ModifierBooleanOps.scala

Add `VDomModifier.ifTrue` and `VDomModifier.ifNot`
Based on #355

Boolean VDomModifier operations

---

build.sbt
outwatch/src/main/scala/outwatch/EmitterBuilder.scala
outwatch/src/main/scala/outwatch/definitions/DomTypes.scala
outwatch/src/main/scala/outwatch/definitions/OutwatchAttributes.scala
outwatch/src/main/scala/outwatch/helpers/NativeHelpers.scala
outwatch/src/main/scala/outwatch/package.scala
project/plugins.sbt
tests/src/test/scala/outwatch/DomEventSpec.scala
tests/src/test/scala/outwatch/OutWatchDomSpec.scala
tests/src/test/scala/outwatch/OutwatchSpec.scala
tests/src/test/scala/outwatch/ScenarioTestSpec.scala
tests/src/test/scala/outwatch/SnabbdomSpec.scala
util/src/main/scala/outwatch/util/Http.scala
util/src/main/scala/outwatch/util/LocalStorage.scala

Supersedes https://github.com/outwatch/outwatch/pull/534 and https://github.com/outwatch/outwatch/pull/539. Also bumps colibri to the latest hash.
This is almost ready, except for some trickyness I will point out and would appreciate some feedback on. Thanks!

Update to scalajs-dom 2.0.0 and domtypes 0.15.0

---

outwatch/src/main/scala/outwatch/ChildCommand.scala
outwatch/src/main/scala/outwatch/OutWatch.scala
outwatch/src/main/scala/outwatch/Render.scala
outwatch/src/main/scala/outwatch/VDomModifier.scala
outwatch/src/main/scala/outwatch/helpers/OutwatchTracing.scala
outwatch/src/main/scala/outwatch/interpreter/ModifierToSnabbdom.scala
outwatch/src/main/scala/outwatch/interpreter/SnabbdomOps.scala
tests/src/test/scala/outwatch/AttributeSpec.scala
tests/src/test/scala/outwatch/OutWatchDomSpec.scala
tests/src/test/scala/outwatch/RepairDomSpec.scala

- always write to the console
- render an error element with the exception into the dom
fixes #544

handle errors properly in dynamic content (IO/Observables)

---

build.sbt
docs/readme.md

Explicitly mention mdoc preview mechanisms

---

build.sbt
snabbdom/yarn.lock

https://github.blog/2021-09-01-improving-git-protocol-security-github

Fix npm github dependency

---

outwatch/src/main/scala/outwatch/definitions/DomTypes.scala
outwatch/src/main/scala/outwatch/helpers/Builder.scala
tests/src/test/scala/outwatch/AttributeSpec.scala

accum for style attributes

---

tests/src/test/scala/outwatch/OutWatchDomSpec.scala

add tests for patch events in and outside of observable

---

outwatch/src/main/scala/outwatch/helpers/StatefulOberver.scala
outwatch/src/main/scala/outwatch/interpreter/ModifierToSnabbdom.scala
outwatch/src/main/scala/outwatch/interpreter/SnabbdomOps.scala
tests/src/test/scala/outwatch/OutWatchDomSpec.scala

@fdietze the last commit should be the fix for a bug that you encountered!
based on #593

direct subscription on render

---

outwatch/src/main/scala/outwatch/VModifier.scala
outwatch/src/main/scala/outwatch/implicits.scala
outwatch/src/main/scala/outwatch/interpreter/SnabbdomOps.scala
tests/src/test/scala/outwatch/ImplicitsSpec.scala

This reverts commit 50b88ceea4be335524c24f55c0ac33ba324655e8.

add implicits for VNode operations on Functor

---

build.sbt
docs/readme.md
outwatch/src/main/scala/outwatch/AttrBuilder.scala
outwatch/src/main/scala/outwatch/EmitterBuilder.scala
outwatch/src/main/scala/outwatch/VMod.scala
outwatch/src/main/scala/outwatch/definitions/DomTypes.scala
outwatch/src/main/scala/outwatch/definitions/OutwatchAttributes.scala
outwatch/src/main/scala/outwatch/package.scala

- **remove deprecations**
- **update colibri**

remove deprecations
